name: CI Pipeline

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/**"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build project (skip tests)
        run: mvn clean verify -DskipTests
        working-directory: ./backend/sb-ecom

      - name: Package application
        run: mvn package -DskipTests
        working-directory: ./backend/sb-ecom

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ecommerce-app
          path: backend/sb-ecom/target/*.jar
          retention-days: 50
